import "~/styles/globals.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/700.css";

import { type Metadata } from "next";
import { Inter } from "next/font/google";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

import { TRPCReactProvider } from "~/trpc/react";
import { ChatStoreProvider } from "~/lib/chat-store";
import { LayoutContent } from "./_components/layout-content";
import { Toaster } from "~/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`dark ${inter.variable}`}>
      <body className="min-h-dvh bg-[#071315] text-neutral-100 overflow-hidden">
        <TRPCReactProvider>
          <ChatStoreProvider>
            <LayoutContent>{children}</LayoutContent>
            <Toaster richColors position="top-right" />
          </ChatStoreProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
